x-airflow-common: &airflow-common
  image: ${MWAA_IMAGE_REPOSITORY:-amazon-mwaa-docker-images/airflow}:${MWAA_IMAGE_TAG:-3.0.6-dev}
  init: true
  env_file:
    - ./config/.env.localrunner
  environment:
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-FAKE_AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-FAKE_AWS_SECRET_ACCESS_KEY}
    AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-FAKE_AWS_SESSION_TOKEN}
    AWS_REGION: ${AWS_DEFAULT_REGION:-us-west-2}
    AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-west-2}
    MWAA__CORE__REQUIREMENTS_PATH: /usr/local/airflow/requirements/requirements.txt
    MWAA__CORE__FERNET_KEY: ${MWAA__CORE__FERNET_KEY:-{"FernetKey":"nNge+lks3RBeGVrnZ1Dq5GjKerbZKmb7dXNnsNsGy3E="}}
    MWAA__DB__CREDENTIALS: '{"username": "airflow", "password": "airflow"}'
    MWAA__DB__POSTGRES_DB: airflow
    MWAA__DB__POSTGRES_HOST: postgres
    MWAA__DB__POSTGRES_PORT: "5432"
    MWAA__DB__POSTGRES_SSLMODE: prefer
    MWAA__SQS__CREATE_QUEUE: "True"
    MWAA__SQS__CUSTOM_ENDPOINT: http://sqs:9324
    MWAA__SQS__QUEUE_URL: http://sqs:9324/000000000000/celery-queue
    MWAA__SQS__USE_SSL: "False"
  volumes:
    - ../dags:/usr/local/airflow/dags
    - ../plugins:/usr/local/airflow/plugins
    - ../requirements:/usr/local/airflow/requirements
    - ../logs:/usr/local/airflow/logs
  depends_on:
    postgres:
      condition: service_healthy
    sqs:
      condition: service_healthy

services:
  postgres:
    image: public.ecr.aws/docker/library/postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ../db-data-pg13:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  sqs:
    image: softwaremill/elasticmq:latest
    healthcheck:
      test: ["CMD-SHELL", "wget -q -S -O - 127.0.0.1:9324/?Action=ListQueues"]
      interval: 10s
      timeout: 5s
      retries: 5

  resetdb:
    <<: *airflow-common
    command: resetdb
    restart: "no"
